### ISSUE TITLE
ML Vision Barcode Detector - VisionBarcode.dispayValue is always nil

### ISSUE THREAD

**Issue by maxim-ivashkevich** [firebase/quickstart-ios#481]
I faced with that issue in my own project but noticed that `quickstart-ios/mlvision` has the same issue:

When you're trying to detect a barcode at one of the embedded images (barcode_128.jpg or qr_code.jpg) `displayValue` is always `nil`.

(FirebaseMLVision (0.10.0), FirebaseMLVisionBarcodeModel (0.10.0))

**Comment by morganchen12** [comment]
I'm unable to reproduce this, running the sample gives me nonnull `displayValue`s for both the images specified. What version of MLKit are you using?

**Comment by maxim-ivashkevich** [comment]
All FirebaseML~ modules have 0.10.0 version. 

<details><summary>Here's what I'm getting:</summary><p>

![embeddedimage1](https://user-images.githubusercontent.com/3875733/41921349-5e955eac-796b-11e8-935b-12a93e6de693.png)
![embeddedimage2](https://user-images.githubusercontent.com/3875733/41921350-5eb77e56-796b-11e8-9253-0cf90c387cfa.png)
![externalimage1](https://user-images.githubusercontent.com/3875733/41921351-5ed89064-796b-11e8-9b0b-0e09e723ce70.png)

</p></details>

**Comment by morganchen12** [comment]
Disregard my last comment, I've been able to reproduce this with the sample images.

I'll let the MLKit team know and keep this ticket updated.

**Comment by morganchen12** [comment]
b/110845379

**Comment by morganchen12** [comment]
Fix up at cr/204789160

**Comment by morganchen12** [comment]
This is fixed and will be out in the next MLKit update.

**Comment by maxim-ivashkevich** [comment]
Hi @morganchen12 . Just wanted to clarify:
I've updated to the latest FirebaseMLVisionBarcodeModel 0.11.0 version and, unfortunately, the issue is still there. So, it there any approximate date when the fix will be released?

**Comment by morganchen12** [comment]
Sorry for the confusion. The bug is part of GoogleMobileVision, which isn't part of the normal Firebase release cycle, so the fix wasn't pushed with the last Firebase release. It should be out in the next week or two.

**Comment by maxim-ivashkevich** [comment]
Hi @morganchen12. Sorry for disturbing you again. I'm still waiting for this fix to be released but it still not there. Is there any updated ETA for it?

**Comment by morganchen12** [comment]
I've asked the GMV team and will let you know. Apologies for the delay.
