### ISSUE TITLE
Error 501 when registering for push notifications

### ISSUE THREAD

**Issue by luccascorrea** [firebase/quickstart-ios#56]
I migrated an existing GCM app to Firebase and implemented all methods exactly like the sample code. However, I keep getting an error whenever the app tries to get an instance id. The logged messages are:

	2016-07-05 16:41:49.298: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "The operation couldn’t be completed. (com.firebase.iid error 501.)"
	2016-07-05 16:42:01.676: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "The operation couldn’t be completed. (com.firebase.iid error 501.)"
	2016-07-05 16:42:26.735: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "The operation couldn’t be completed. (com.firebase.iid error 501.)"
	2016-07-05 16:43:05.580: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "The operation couldn’t be completed. (com.firebase.iid error 501.)"
	2016-07-05 16:44:03.260: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "The operation couldn’t be completed. (com.firebase.iid error 501.)"
	2016-07-05 16:44:03.261: <FIRInstanceID/WARNING> Failed to retrieve the default GCM token after 5 retries

Does anyone know why this happens? I contacted Firebase support and they couldn't help. 

Knowing that this is an app that was working fine before switching to Firebase, I know that push configurations on the app side are working. And considering that all the configuration on the Firebase Console was imported from my previous Google Project, I would assume that my certificates are all working as well.

Does anyone have any clue what I could do to solve this?

**Comment by dnnyg33** [comment]
bump

**Comment by eclipsegst** [comment]
I met this issue early, i found out i didn't upload certificate(.p12 file) in Firebase console. 
I solved this issue by going to firebase console, click settings icon in left top corner-> Project settings -> cloud messaging -> update .p12 file, rebuild my app

**Comment by kroikie** [comment]
@luccascorrea is this still an issue for you?

**Comment by kroikie** [comment]
I'm closing this issue, as I believe it has been resolved. Feel free to open a new issue if you are still running into this.

**Comment by supriya-mobantica** [comment]
Hi, I am still facing the same issue. Cross verified all the settings. Also uploaded development p12 certificate, but getting same error:
2016-11-17 12:04:49.251: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "(null)"
2016-11-17 12:05:14.662: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "(null)"
2016-11-17 12:05:59.066: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "(null)"
2016-11-17 12:07:03.187: <FIRInstanceID/WARNING> Failed to fetch default token Error Domain=com.firebase.iid Code=501 "(null)"
2016-11-17 12:07:03.187: <FIRInstanceID/WARNING> Failed to retrieve the default GCM token after 5 retries

Surprisingly,  it works fine on simulator, but when I try same on device, giving me error.  I am stuck, any help is appreciated.

**Comment by ManishBTC** [comment]
I am also facing this issue. Strange thing is I am facing this issue ony on very few devices. Is it something related to iOS version?
